version: '3.8'
services:
  stats-server:
    build: ./ewm-stats-service
    container_name: "ewm-stats"
    ports:
      - "9090:9090"
    depends_on:
      - ewm-service
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: "ewm-stats-bd"
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./ewm-main-service
    container_name: "ewm-main"
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - stats-server.url=http://ewm-stats-service:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root


  ewm-db:
    image: postgres:14-alpine
    container_name: "ewm-main-db"
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
