CREATE TABLE IF NOT EXISTS stats
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(128)                            NOT NULL,
    uri       VARCHAR(1024)                           NOT NULL,
    ip        VARCHAR(1024)                           NOT NULL,
    timestamp TIMESTAMP                               NOT NULL,
    CONSTRAINT "pk_Stats" PRIMARY KEY (id)
);
